version: '3.3'

services:
  nginx:
    image: nginx
    ports:
      - 8080:80

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: task-manager-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  user-service-1:
    container_name: user-service-1
    build:
      dockerfile: user-service/Dockerfile
    ports:
      - 11001:8080
    depends_on:
      - nginx
      - postgres
  user-service-2:
    container_name: user-service-2
    build:
      dockerfile: user-service/Dockerfile
    ports:
      - 11002:8080
    depends_on:
      - nginx
      - postgres