# This is a basic workflow to help you get started with Actions

name: FeaturePipeline

# Controls when the workflow will run
on:
  push:
    branches: [ "feature/**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build
      run: gradle clean build
