name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Run tests
        run: gradle test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Copy project files to remote server
        run: |
          rsync -avz --exclude='.git/' . root@185.121.134.83:/task-manager

      - name: Deploy with Docker Compose
        run: |
          ssh root@185.121.134.83 "cd /task-manager && \
          gradle build -x test && \
          docker-compose -f docker-compose-production.yml down && docker-compose -f docker-compose-production.yml up -d"